### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/helm-backstage#114]
### What do you want to improve?

Would like to be able to set labels.

**Comment by Zaperex** [comment]
I believe the upstream backstage chart already provides the ability to apply common labels:
https://github.com/backstage/charts/blob/f50465f9907f639fcbc4c99a5c197fdaf8f92bbd/charts/backstage/values.yaml#L32-L33
Which can be found in the janus helm chart at `upstream.properties.commonLabels` which should apply the labels to all the deployed objects. From testing, it appears that [ONLY the deployment](https://github.com/backstage/charts/blob/c6f1c5c5c6aae86333ea8dcbcd073105e6170570/charts/backstage/templates/backstage-deployment.yaml#L11-L14) (not the pods or postgres resources) get the applied label.
https://github.com/janus-idp/helm-backstage/blob/417057a128e7192bce6f1a6f55a594c25a856bf2/charts/backstage/values.schema.json#L4044-L4051

We can also use the `upstream.properties.backstage.properties.podLabels` field in the values.yaml to include the labels for the backstage [deployment's pods](https://github.com/backstage/charts/blob/c6f1c5c5c6aae86333ea8dcbcd073105e6170570/charts/backstage/templates/backstage-deployment.yaml#L32-L34) (The deployment itself doesn't get this label, only the pods do): https://github.com/janus-idp/helm-backstage/blob/417057a128e7192bce6f1a6f55a594c25a856bf2/charts/backstage/values.schema.json#L3732-L3739

So to get labels on both the backstage deployment and the backstage deployment's pods, the end user will need to apply both. 

Currently it doesn't seem there's a way to apply labels via the helm chart for the other resources (ex: postgres stateful set, route resources, service resources, etc.)
Additionally, neither of these values are visible in the Form view on openshift, so it would require the end-user to directly modify the `values.yaml` via the YAML view.

**Comment by Zaperex** [comment]
It appears that the [backstage upstream chart](https://github.com/backstage/charts/blob/c6f1c5c5c6aae86333ea8dcbcd073105e6170570/charts/backstage/values.yaml#L314-L316) uses a bitnami postgreSQL chart which appears to also have a [`commonLabel`](https://github.com/bitnami/charts/blob/0f96d865389bff040a1cea62022d9f348fd15ce0/bitnami/postgresql/values.yaml#L66) field. However, when I put the `commonLabel` in the values.yaml:
```yaml
upstream:
  nameOverride: backstage
  backstage:
    # backstage configs
  commonLabels:
    test: label
  postgresql:
     # postgresql configs
```
Only the backstage resources (excluding pods) get the `commonLabels` labels, while the postgresql resources do not for some reason, despite the postgresql chart also uses the `commonLabels` values when creating labels for its resources

**Comment by kadel** [comment]
> Only the backstage resources (excluding pods) get the commonLabels labels, while the postgresql resources do not for some reason, despite the postgresql chart also uses the commonLabels values when creating labels for its resources

I think this is expected. The values are not inherited into nested Charts like this.
To set labels for `postgresql` you need to put `commonLabels` to `postgresql` section.


```yaml
upstream:
  nameOverride: backstage
  backstage:
    # backstage configs
  commonLabels:
    test: label
  postgresql:
    commonLabels:
      test: label
    # postgresql configs

```
