### ISSUE TITLE
Unable to use chart published to OCP helm charts repository as a dependency

### ISSUE THREAD

**Issue by tumido** [janus-idp/helm-backstage#135]
### Describe the bug

Raising awareness of this bug: https://github.com/openshift-helm-charts/charts/issues/773

### Expected Behavior

Chart deploys

### What are the steps to reproduce this bug?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  redhat-developer-hub


helmCharts:
  - name: developer-hub
    releaseName: redhat-developer-hub
    namespace: redhat-developer-hub
    repo: https://charts.openshift.io/
    valuesFile: values.yaml
```

After `oc apply` or via ArgoCD, it results in:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build <path to cached source>/clusters/hub/overlays/redhat-developer-hub --enable-alpha-plugins --load-restrictor LoadRestrictionsNone --helm-command /usr/local/bin/helm` failed exit status 1: Error: Error: chart "developer-hub" not found in https://charts.openshift.io/ repository : unable to run: '/usr/local/bin/helm pull --untar --untardir <path to cached source>/clusters/hub/overlays/redhat-developer-hub/charts --repo https://charts.openshift.io/ developer-hub' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-83159299/helm HELM_CACHE_HOME=/tmp/kustomize-helm-83159299/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-83159299/helm/.data] (is '/usr/local/bin/helm' installed?): exit status 1
```

### Versions of software used and environment
N/A
