### ISSUE TITLE
Postgresql `volumeClaimTemplate` is ArgoCD incompatible

### ISSUE THREAD

**Issue by tumido** [janus-idp/helm-backstage#137]
### Describe the bug

Deploying the chart results in `VolumeClaim` to be created from a template. Resources admitted to the cluster do not use the following values:

![image (2)](https://github.com/janus-idp/helm-backstage/assets/7453394/d42ffebd-6b87-4a6d-b93b-63d414ec554e)

### Expected Behavior

Chart doesn't use fields that are not admissible.

### What are the steps to reproduce this bug?

TPB

**Comment by Zaperex** [comment]
@tumido can I get more details on this issue? When I tried replicating this issue on a local argocd server hosted on openshift local, using the `2.11.4` chart, argocd doesn't seem to complain about anything?
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janus-backstage
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://api.crc.testing:6443'
  source:
    path: ''
    repoURL: 'https://janus-idp.github.io/helm-backstage'
    targetRevision: 2.11.4
    chart: backstage
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.clusterRouterBase
          value: apps-crc.testing
        - name: upstream.backstage.image.tag
          value: next
  sources: []
  project: backstage-testing
  ```
  
  The desired manifest for the `volumeClaimTemplate` seems to match the live manifest and I don't seem to see the issue shown in the screenshot for the issue.
  
[Screencast from 2024-01-08 15-43-59.webm](https://github.com/janus-idp/helm-backstage/assets/50030060/9b8ac2be-b227-4f0c-b4e4-91df6d72972e)
