### ISSUE TITLE
postgresql problem

### ISSUE THREAD

**Issue by reechang** [janus-idp/helm-backstage#55]
Hi everyone,

when I am trying to deploy on openshift, this happened:

```
$ helm install backstage-helm janus-idp/backstage -f values-openshift.yaml

coalesce.go:220: warning: cannot overwrite table with non table for postgresql.networkPolicy.egressRules.customRules (map[])
NAME: backstage-helm
LAST DEPLOYED: Thu May 11 17:15:40 2023
NAMESPACE: xxxxxxxxxx
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

And the result is postgresql won't start.

**Comment by tumido** [comment]
Hi @reechang , can you please provide us more details on your `upstream.postgresql` values?

The `coalesce.go:220: warning` is just a schema warning caused by invalid JSON schema for `bitnami/postgres` chart dependency upstream, it has no impact on the deployed resources. As you can see the status says *deployed*.

This is not the cause of your issues, we need to investigate further. 🙂

**Comment by reechang** [comment]
Hi @tumido , thanks for your quick reply :)

Basically, I am using the template from [janus-idp](https://janus-idp.io/blog/deploying-backstage-onto-openshift-using-helm)

Here is my `postgresql` values

```
 postgresql:
    enabled: true
    database: backstage
    postgresqlDataDir: /var/lib/pgsql/data/userdata
    auth:
      username: postgres
      database: backstage
    image:
      registry: registry.redhat.io
      repository: rhel9/postgresql-13
      tag: 1-73
    primary:
      securityContext:
        enabled: false
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      persistence:
        enabled: true
        mountPath: /var/lib/pgsql/data
      extraEnvVars:
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: backstage-postgresql
```
