### ISSUE TITLE
Openshift Helm catalog is unable to pull remote JSON schemas on OpenShift Local

### ISSUE THREAD

**Issue by tumido** [janus-idp/helm-backstage#64]
Clicking the Install Helm chart button results in different outcomes depending on the cluster location:
![image](https://github.com/janus-idp/helm-backstage/assets/7453394/9491fb15-abf4-46e4-9bd3-9bf3c8d0a0f1)

# OpenShift Local

![image](https://github.com/janus-idp/helm-backstage/assets/7453394/e3784d1a-247b-4407-a4c5-1f678310965c)

# Developer Sandbox

![image](https://github.com/janus-idp/helm-backstage/assets/7453394/64d2029e-ba86-459b-9c6c-b3eef801777f)

# OpenShift (aka remote cluster, non-restricted)

![image](https://github.com/janus-idp/helm-backstage/assets/7453394/e387deb8-4958-4a8c-806e-80ccb2dcd39d)

I think we need to inline the remote JSON schema references... Unfortunately. This will expose us to copy-paste errors. It's not a great solution.

**Comment by tumido** [comment]
I'll try to provide a postprocessing step for `values.schema.json` via https://github.com/APIDevTools/json-schema-ref-parser or similar tool.

**Comment by serenamarie125** [comment]
Launching a 4.9 cluster via cluster-bot is also issue, although it produces different results than a 4.13 cluster


![BackstageHelmChart-4 9-ClusterBot](https://github.com/janus-idp/helm-backstage/assets/12504403/772b894e-bcba-438f-a156-903e459a33e0)

**Comment by tumido** [comment]
@serenamarie125 wow, that is an especially weird one. 😂

I've created sample helm repo from the PR #66 to see if it works. Can you please try creating new Helm repository in the catalog and installing backstage from it? It works for me now in DevSandbox

```yaml
apiVersion: helm.openshift.io/v1beta1
kind: ProjectHelmChartRepository
metadata:
  name: test-repo
spec:
  connectionConfig:
    url: 'https://raw.githubusercontent.com/tumido/helm-backstage/test-repo'
```
