### ISSUE TITLE
Simplify default values that are necessary to be configured when deploying to OpenShift 

### ISSUE THREAD

**Issue by tumido** [janus-idp/helm-backstage#72]
If user chooses the most likely path of default deploy, let's remove most of the manual labor from the process. Currently they have to essentially copy paste a value into 3 different places. Let's streamline this into a single default.

```yaml
 upstream:
   backstage:
     appConfig:
       app:
         baseUrl: 'https://{{- print .Release.Name "-" .Release.Namespace -}}.apps.example.com'
       backend:
         baseUrl: 'https://{{- print .Release.Name "-" .Release.Namespace -}}.apps.example.com'
         cors:
           origin: 'https://{{- print .Release.Name "-" .Release.Namespace -}}.apps.example.com'
```
